package protocol


// VoucherStatus indicate the domain record data fields.
type VoucherStatus interface {
	VoucherID() [16]byte    //
	Status() Voucher_Status //
	Time() protocol.Time    // save time
	RequestID() [16]byte    // user-request domain
}

type VoucherStatus_StorageServices interface {
	Save(vs VoucherStatus) (numbers uint64, err protocol.Error)

	Count(voucherID [16]byte) (numbers uint64, err protocol.Error)
	Get(voucherID [16]byte, versionOffset uint64) (vs VoucherStatus, numbers uint64, err protocol.Error)

	FilterByStatus(status Voucher_Status, offset, limit uint64) (voucherIDs [][16]byte, numbers uint64, err protocol.Error)
}

type Voucher_Status Quiddity_Status

const (
	Voucher_Status_AutoGenerated = Voucher_Status(Quiddity_Status_FreeFlag << iota)
	Voucher_Status_FirstInvoice

	Voucher_Status_PartlyUsed
	Voucher_Status_FullyUsed

	Voucher_Status_Expired
	Voucher_Status_Revoked
)
